version: '3.5'

services:
  identifier:
    restart: "no"
    ports:
      - "8080:80"
  dispatcher:
    restart: "no"
  frontend:
    restart: "no"
  virtuoso:
    restart: "no"
    ports:
      - "8890:8890"
  database:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  deltanotifier:
    restart: "no"
  file:
    restart: "no"
  harvesting-download-url:
    environment:
      CACHING_MAX_RETRIES: 5
    restart: "no"
  harvest-collector:
    restart: "no"
  harvesting-import:
    restart: "no"
  harvesting-sameas:
    restart: "no"
  job-controller-service:
    restart: "no"
  scheduled-job-controller-service:
    restart: "no"
